### ISSUE TITLE
Integrate Pattern Lab into Theme

### ISSUE THREAD

**Issue by coreylafferty** [forumone/generator-web-starter#10]
- Add Gesso to build (if it isn't already).  http://drupal.org/project/gesso/
- Add Pattern Lab to build (https://github.com/dcmouyard/patternlab-php-gesso).  The contents of that repo should be dropped into a folder at /sites/all/themes/gesso/patternlab/
- Create yeoman builders to create theme + PL
- /sites/all/themes/gesso/patternlab/public/ should have permissions set to be accessible (so easily viewed on dev/stage site).  If possible, could be set to inaccessible by default on production -- or could simply be set to only build the patternlab public files on dev/stage.

**Comment by dcmouyard** [comment]
I’d prefer if Pattern Lab was dropped into the `/sites/all/themes/gesso/pattern-lab/` directory.

Also, in addition to having `/sites/all/themes/gesso/pattern-lab/public/` be publicly accessible, nginx (or apache?) should allow index.html as the index file for that directory.

**Comment by wwhurley** [comment]
There is a gesso sub-generator that prompts to install Pattern Lab and drops it into the named theme.
