### ISSUE TITLE
Diff from a manually-created project shows some oddities

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/generator-web-starter#21]
I generated a yeoman project for CSIS and compared it to my manually created version... It left some defaults that I thought were important, and set some variables that seem odd to me. Some of this is probably my limited understanding, but I suspect that some of it comes from real bugs.

/Gemfile: 
```diff
 # Load gem dependencies from the theme
-theme_gemfile = File.join(File.dirname(__FILE__), "public/sites/all/themes/csis_theme/Gemfile")
+theme_gemfile = File.join(File.dirname(__FILE__), "public/sites/all/themes/gesso/Gemfile")
```
* Why doesn't it ask me for my theme directory? Should I still make this change manually?

/config/deploy.rb:
```diff
 @@ -1,11 +1,8 @@
 # The name for the application, should only be things that can be in a directory name
-set :application, 'app'
+set :application, 'csis'
 
 # The repo URL
-set :repo_url, 'repo'
-
+set :repo_url, 'git@github.com:forumone/csis.git'
 
 # Or use the line below to deploy via rsync
 set :scm, :rsync
```
* is :application actually used? I've always left it default.
* is :repo_url used if using rsync deployment?

config/deploy/dev.rb (also applies to stage.rb and live.rb):
```diff
 # An array containing site URL, used for Varnish bans
-set :site_url, %w{dev.csis.byf1.io}
+set :site_url, %w{example.com}
 
 # An array containing drupal sites to copy settings files in
 set :site_folder, %w{default}
@@ -11,7 +11,7 @@ set :site_folder, %w{default}
 set :webroot, 'public'
 
 # The path to the project on the server
-set :deploy_to, '/var/www/vhosts/csis.dev'
+set :deploy_to, '/var/www/vhosts/example.com'
 
 # Where the temporary directory is
 set :tmp_dir, fetch(:deploy_to)
@@ -24,9 +24,9 @@ set :branch, "master"
 # Supports bulk-adding hosts to roles, the primary
 # server in each group is considered to be the first
 # unless any hosts have the primary property set.
-role :app, %w{csis@dev.csis.byf1.io}, :primary => true
-role :web, %w{csis@dev.csis.byf1.io}
-role :db,  %w{csis@dev.csis.byf1.io}
+role :app, %w{deploy@example.com}, :primary => true
+role :web, %w{deploy@example.com}
+role :db,  %w{deploy@example.com}
```

* do we not use :site_url anymore?
* do we not use :deploy_to anymore?
* role definition is inconsistent between dev, stage, and live. Why? 
* stage.rb sets :stage to the project name. Is that right?

**Comment by wwhurley** [comment]
Did you select "basic" or "advanced" when using the yeoman generator?

**Comment by ohthehugemanatee** [comment]
"advanced", though most of my answers were default. Should I use "basic" and see if it resolves some of these questions?

**Comment by wwhurley** [comment]
Ahhh... right. I almost forgot there is a separate sub-generator for Capistrano stages. You'll want to run "yo web-starter:stage [stage name]" or "yo web-starter:stage dev" for the dev deployment target. Right now the questions are basically just the names of the variables, so it's a little jargony -- one of the things that needs to get changed.

**Comment by ohthehugemanatee** [comment]
added to the README.
