### ISSUE TITLE
PHP Version Selection Has No Effect

### ISSUE THREAD

**Issue by slucero** [forumone/generator-web-starter#25]
Selecting an alternative PHP verison (in this case PHP55) from the setup questions has no effect on installation.

- **Installed generator version**: forumone/generator-web-starter@95fb3e929ecea5c123f65b62a56f6c60bb62edac
- **Web starter version used**: forumone/web-starter@414e2aefe6be407eef0986e1f0c9684d42782761

### `.yo-rc.json` produced

```json
{
  "generator-web-starter": {
    "install_type": "advanced",
    "name": "project_api",
    "version": "0.1.0",
    "refspec": "1.1.x",
    "platform": "drupal",
    "repository": "",
    "puppet": true,
    "host": "f1dev",
    "app_webroot": "lumen/public",
    "db_name": "web",
    "db_user": "web",
    "php_prefix": "php55",
    "use_capistrano": true,
    "deploy_via": "rsync",
    "keep_releases": 3,
    "use_compass": false,
    "use_patternlab": false,
    "features": false,
    "cmi": false,
    "solr": false
  }
}
```

### `localhost.localdomain.yaml` produced

```ruby
---
forumone::databases: 
  web: 
    username: web

forumone::webserver::vhosts:  
  vagrant: 
    path: "/vagrant/lumen/public"
```

**Comment by wwhurley** [comment]
This was resolved by https://github.com/forumone/generator-web-starter-puppet/commit/d639b2a7f4e71273254859cd105b09950a9d124e.
