### ISSUE TITLE
generator-web-starter@0.4.0 requires a peer of yo@>=1.0.0-rc.1 but none was installed.

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/generator-web-starter#28]
On trying to install (per the wiki) with npm -g generator-web-starter , I get:

<code>
npm WARN EPEERINVALID generator-web-starter@0.4.0 requires a peer of yo@>=1.0.0-rc.1 but none was installed.
npm WARN EPEERINVALID generator-web-starter-drupal@0.0.1 requires a peer of yo@>=1.0.0-rc.1 but none was installed.
npm WARN EPEERINVALID generator-web-starter-wordpress@0.0.1 requires a peer of yo@>=1.0.0-rc.1 but none was installed.
npm WARN EPEERINVALID generator-web-starter-capistrano@0.0.1 requires a peer of yo@>=1.0.0-rc.1 but none was installed.
npm WARN EPEERINVALID generator-web-starter-puppet@0.0.1 requires a peer of yo@>=1.0.0-rc.1 but none was installed.
npm ERR! code 1
</code>

It does not disappear after I manually install yeoman with "npm install -g yo". But it seems to work fine regardless.. though it no longer asks me any questions about my project apart from the basics (name, version). I haven't used this tool in a few months so I don't know if that's normal or not.

**Comment by wwhurley** [comment]
The generator requires Yeoman to be installed separately. Peer dependencies with NPM have changed somewhat in that they will only warn not actually install the dependency. The plugin issue is being addressed in #27.
