### ISSUE TITLE
Indicate Web Starter Hash In Generated Projects

### ISSUE THREAD

**Issue by slucero** [forumone/generator-web-starter#31]
When debugging configuration issues with web starter it's helpful to know what version of web starter was installed. Adding this in some way to projects built on top of it would be very helpful in these cases. Adding a version number is one option, but given the generator tends to pull the latest commit off the specified branch I'd suggest a commit hash since it would be more specific.

The next question is where to track this. To me adding it as a key in `package.json` is the most obvious choice since it's always committed in a project, but other suggestions are welcomed as well.

**Comment by wwhurley** [comment]
We should switch to semver releases for the web-starter repo and bringing in files from there. Between that and separating out functionality into the various sub-generators we should be able to track changes better.
