### ISSUE TITLE
Support Custom Puppet Modules

### ISSUE THREAD

**Issue by johnbburg** [forumone/generator-web-starter#32]
I have a project which I've added some additional custom puppet modules, which I define in the PuppetFile. However, If I want to update the web-starter configuration, I need to allow the generator to overwrite my module settings in the PuppetFile, and then re-add the custom modules. 

What is the procedure for including additional puppet modules?

**Comment by wwhurley** [comment]
Custom Puppet modules can be added to the Puppetfile and Puppetfile.lock files. From there they'll be downloaded onto the VM. They can then be included in the classes array in any of the Hiera YAML files -- see https://github.com/forumone/web-starter/blob/1.1.x/puppet/manifests/hieradata/hosts/pantheon.yaml#L7 for example. From there any configuration can be also managed through Hiera, generally in the localhost.localdomain.yaml file.
