### ISSUE TITLE
Fix yo@>=1.0.0-rc.1 peer dependency warnings

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#36]
![screen shot 2016-03-15 at 9 56 29 am](https://cloud.githubusercontent.com/assets/696005/13786334/4d2d28c4-ea94-11e5-8837-9f03d7f99c7e.png)

My generator seems to be working, so I don't know if this is an actual problem.  But fixing or explaining the warnings would help us onboard new developers to our process.  This one makes it sound like something is broken.

**Comment by mortona42** [comment]
![screen shot 2016-03-15 at 10 07 54 am](https://cloud.githubusercontent.com/assets/696005/13786641/d56497e4-ea95-11e5-8d49-83276ad55685.png)

This one pops up when I update generator-web-starter.

**Comment by wwhurley** [comment]
I believe these are done. Can you verify, @tla-dev?

**Comment by tla-dev** [comment]
yes it is fixed
