### ISSUE TITLE
theme_path is not defined

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#37]
![screen shot 2016-03-15 at 10 14 44 am](https://cloud.githubusercontent.com/assets/696005/13786910/fe925e0c-ea96-11e5-8c3a-b656c2282c2e.png)

Trying to run yo to update an existing site.

**Comment by wwhurley** [comment]
You need to run `git pull` and then `npm install` to get the latest versions of generator and sub-generators. If you had installed it using `npm install -g` you'll need to re-run `npm install -g generator-web-starter`
