### ISSUE TITLE
Configure site_url, deploy_to in deploy config via yeoman

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#38]
These are manual steps that have to be repeated when you update your web starter instance.  If we add them to the yeoman config, we won't have to worry about it again.

**Comment by wwhurley** [comment]
There was a generator for Capistrano stages that had to be removed during the refactoring into separate sub-generators. It's on our roadmap to add that functionality back to the Capistrano sub-generator.

**Comment by wwhurley** [comment]
Creating Capistrano stages is part of the Capistrano sub-generator and is invoked using `yo web-starter-capistrano [stage]`
