### ISSUE TITLE
Overwrites values in config/deploy/*.rb

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/generator-web-starter#53]
I just ran generator-web-starter on an existing project (which was created with an earlier version of generator-web-starter). It overwrote normal customizations in deploy configurations with example.com values:

* ```set :site_url, %w{example.com}``` 
* ```set :webroot, 'public'``` 
* ```set :deploy_to, '/var/www/vhosts/example.com'``` 
* all of the roles

These values appear to be stored in ```.yo-rc.json```, but aren't exposed in questions. I appreciate that it adds a lot of questions to the process - perhaps they could be wrapped into one big "accept existing/example values for capistrano deployment?" question so existing projects could skip them.

**Comment by wwhurley** [comment]
We'll be migrating default configuration out of the main web-starter repository so they will not be overwritten.

**Comment by wwhurley** [comment]
Resolved by https://github.com/forumone/generator-web-starter/commit/28e58b784740fafc0a448d2fac569e6c3e13c78e which removed the pulling from the forumone/web-starter.
