### ISSUE TITLE
Update installation versions of Gesso and Pattern Lab

### ISSUE THREAD

**Issue by coreylafferty** [forumone/generator-web-starter#59]
**Gesso for Drupal 7:**
New projects should the 7.x-2.x branch, which uses LibSass.
https://github.com/forumone/gesso/tree/7.x-2.x

If installation needs to take into account older projects , the 7.x-1.x branch uses Compass.
https://github.com/forumone/gesso/tree/7.x-1.x

**Gesso for Drupal 8:**
New projects should use the 8.x-1.x branch
https://github.com/forumone/gesso/tree/8.x-1.x

**Gesso for WordPress**
New projects should use the master branch
https://github.com/forumone/gesso-theme-wordpress

**Pattern Lab** 
All versions of Gesso should use the Twig version of Pattern Lab and the Gesso Starterkit.  To install, run this from the theme folder (or adjust the pattern-lab folder path accordingly):

`$ composer create-project pattern-lab/edition-drupal-standard pattern-lab` 

When prompted, select /forumone/starterkit-twig-drupal-gesso as the starterkit. 
_(alternately, the following command can be run to install the starterkit: 
`$ php core/console --starterkit --install forumone/starterkit-twig-drupal-gesso`_ )

If prompted, select 'r' to overwrite existing /source/ files.

**Comment by wwhurley** [comment]
When do we plan to release the 8.x branch of Gesso on drupal.org, @coreylafferty or @dcmouyard?

**Comment by wwhurley** [comment]
Is there an alternate way of downloading the files other than composer? We cannot guarantee that Composer, or a particular version of PHP is installed on the host.

**Comment by dcmouyard** [comment]
There’s now a dev release on Drupal.org for the 8.x branch.

Now that Pattern Lab v2.0 has been released, the node.js version should work just as well as the PHP version. I’ll play around with that to see how it works. @wwhurley
