### ISSUE TITLE
[drupal8] Create an option to use Drupal Composer

### ISSUE THREAD

**Issue by fafnirical** [forumone/generator-web-starter#61]
Drupal projects can use Composer to download PHP dependencies (including Drupal core). We should (optionally?) download [Drupal Composer](https://github.com/drupal-composer/drupal-project/), which sets up a composer.json file and some supporting scripts.

_Note: Drupal 7 also supports Composer, but Drupal 7 projects seem unlikely to use it. If you're reading this and would like to use Composer with Drupal 7, see https://github.com/drupal-composer/drupal-project/tree/7.x._

**Comment by fafnirical** [comment]
I've assigned this to myself to submit a PR.

**Comment by fafnirical** [comment]
#72 might be blocking this. Without knowing the webroot, we can't tell Composer where to install Drupal.

**Comment by mortona42** [comment]
I concur, would be awesome to have the yeoman questions configure the resulting composer file you would get from `composer create-project drupal-composer/drupal-project`.  IE choosing a host option (f1/pantheon/acquia) should set your docroot appropriately.  That would resolve #72 as well.
