### ISSUE TITLE
generator-web-starter-drupal has D7-specific templates

### ISSUE THREAD

**Issue by fafnirical** [forumone/generator-web-starter#62]
There are somewhat significant differences between D8's [default.settings.php](https://github.com/drupal/drupal/blob/8.2.x/sites/default/default.settings.php) and `forumone/generator-web-starter-drupal`'s [settings.vm.php](https://github.com/forumone/generator-web-starter-drupal/blob/master/web-starter/templates/public/sites/default/settings.vm.php).

The settings.vm.php template should be tailored for different Drupal versions (one for D7, each minor version for D8?).

**Comment by wwhurley** [comment]
Added Drupal 8 generator in https://github.com/forumone/generator-web-starter/commit/0f54ba96567181b5d082f6b2a26fe8c66c08a677
