### ISSUE TITLE
Generator Fails to build properly

### ISSUE THREAD

**Issue by generalconsensus** [forumone/generator-web-starter#65]
expand doesn't appear to be working -> time for some glob!

https://www.evernote.com/l/AFMoQRuzFKFI0L_LZSGcZ35ulygZDbtf6qgB/image.png

**Comment by tla-dev** [comment]
I'm surprise you have two times Grunt in the select plugins ...

and you are not running the latest version of the generator

can you get the latest source, link it and run it again?
git clone https://github.com/forumone/generator-web-starter.git
npm install; npm link
yo web-starter

**Comment by wwhurley** [comment]
This was resolved by cd88c02d0df7b4fd655372f70629f719ebbf4977. You may need to update the the most recent published release. To do so globally run `npm install -g generator-web-starter` -- note that you may need to run with with elevated permissions.
