### ISSUE TITLE
WordPress projects should have Composer installed

### ISSUE THREAD

**Issue by coreylafferty** [forumone/generator-web-starter#71]
Currently Composer is only installed when the CMS is Drupal.  Pattern Lab now requires Composer for installation and compiling, so we should ensure that Composer is installed on all projects, regardless of CMS selected.

**Comment by mortona42** [comment]
I have been using WP Starter for NORC.  It does some nice things to setup the files and copies things like index.php to the right place.  It uses phpdotenv for environment variables (like database creds), but I wasn't able to get that to work on our dev server.  I also looked into Bedrock, another WP composer starter kit.

I was considering modifying the WP generator to give you a choice of starter kits, but I don't have the availability to do that.  I'm happy to discuss and share notes if you start working on it.
