### ISSUE TITLE
Select drush version

### ISSUE THREAD

**Issue by johnbburg** [forumone/generator-web-starter#73]
Like the title says. provide the drush version as an option when running the generator.

Original problem: The default web-starter setup will install drush 7.1.0. However, this is incompatible with php 5.3.3, which is still used in some Red Hat distributions of PHP. the 7.3.0 release of drush fixed this issue, but it would still be nice to have the version selectable. Otherwise, you need to manually set the version in the puppet config, which can be easily overwritten on subsequent updates to web-starter.

**Comment by johnbburg** [comment]
Started a branch here: https://github.com/forumone/generator-web-starter-drupal/tree/drush-version.

I'm just not sure where/how I need to update the templates. Presumably this will go in localhost.yaml. But under which project?

web-starter: https://github.com/forumone/web-starter/blob/1.1.x/puppet/manifests/hieradata/sites/_localhost.yaml

Or 

generator-web-starter-puppet (seems more likely) https://github.com/forumone/generator-web-starter-puppet/blob/master/web-starter/templates/puppet/manifests/hieradata/sites/localhost.yaml

Or a new one to on generator-web-starter-drupal?

**Comment by mshade** [comment]
This might actually go into the salt generator - which is currently handling the drush installation. If we move to site-local installs of drush, maybe the drupal generator is right?

**Comment by arh1** [comment]
Fwiw, for D8 projects I think we want to start moving Drush out of web-starter altogether, and instead let Composer install site-local Drush per our [Composer/D8](https://forumone.atlassian.net/wiki/display/TECH/How-to%3A+Use+Composer+with+Drupal+8#How-to:UseComposerwithDrupal8-Creatinganewproject) docs. Still a consideration for D7 sites but just throwing it out there :)

**Comment by fafnirical** [comment]
Drush 9 (the only version that supports Drupal 8.4+) will require a site-local install (usually done via composer.json in the project root): http://docs.drush.org/en/master/install/. To continue using `drush` from anywhere, they recommend [drush-shim](https://github.com/webflo/drush-shim).

**Comment by mshade** [comment]
So, right now in the salt generator, we default to pulling the 8.x branch from drush-ops repo. This is set in salt/roots/generated.sls 

The generator does not ask for your specified version (yet?), but it can be overridden by defining your own value in salt/roots/project.sls (which is never touched by the generator, and always takes precedence). 

Thinking about how to handle the shim, we have three scenarios, we want to provide for:

- a default version of globally installed drush
- a specific version of globally installed drush 
- (new) the drush-shim script if site-local drush is expected

I can expand the drush salt formula to install the shim if specified as the version of drush, perhaps.
