### ISSUE TITLE
Drupal 8 generator tries to require request-promise without having it in the dependency list

### ISSUE THREAD

**Issue by wwhurley** [forumone/generator-web-starter#76]
On https://github.com/forumone/generator-web-starter-drupal8/blob/master/web-starter/index.js#L5 it instantiates the `rp` variable. However request-promise is not defined in the package.json file. It doesn't look like `rp` is used in the generator so it can probably be removed.

**Comment by fafnirical** [comment]
Created PR forumone/generator-web-starter-drupal8#2 for this.
