### ISSUE TITLE
SSH hangs during boot on centos 6.8

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#82]
My boot was timing out on default: SSH auth method: private key

I upgraded virtualbox and vagrant to the latest, but still had the issue.

Setting centos to 6.7 in my Vagrant file fixed the problem.

**Comment by mshade** [comment]
I haven't been able to duplicate this. Have you seen it again?

**Comment by mortona42** [comment]
I can't remember how I fixed it.. @arh1 just worked through this issue.

**Comment by arh1** [comment]
Not sure how this happened, but for me a Virtualbox setting had been tweaked: Settings -> Network -> Advanced -> Cable Connected was unchecked. Once I checked that and did a `vagrant reload --provision` I was good again.
