### ISSUE TITLE
Default to PHP 5.6 option

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#83]
![screen shot 2017-01-20 at 2 46 43 pm](https://cloud.githubusercontent.com/assets/696005/22168821/5696f75c-df24-11e6-80aa-74e9970eec27.png)

It looks like 5.3 is selected by default over 5.6.  Let's use the updated version for new projects.

**Comment by mshade** [comment]
Thanks Andrew - assigning to myself to make sure this gets merged upstream in web-starter repo.

**Comment by fafnirical** [comment]
Is this done? I think we can close this, since it's been merged.
