### ISSUE TITLE
Use ESLint and a coding standard

### ISSUE THREAD

**Issue by fafnirical** [forumone/generator-web-starter#84]
We should use ESLint to lint our code. I'd suggest using the [Airbnb](https://github.com/airbnb/javascript) standard (see [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) for the NPM package), as it's the most commonly used standard and will soon be used by Drupal core.

**Comment by wwhurley** [comment]
Several of the generators have had ESLint configuration added. I'll be putting this in the rest of them on an ongoing basis.
