### ISSUE TITLE
Give Vim sensible default config in vimrc

### ISSUE THREAD

**Issue by abielefeldt** [forumone/generator-web-starter#85]
On a new web-starter VM, Vim doesn't have certain helpful things out of the box like expanded, 2-space tabs, or line numbers, or syntax highlighting for non-*.php files. vimrc should have something along these lines on a new VM:

> set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
> 
> au BufNewFile,BufRead *.module set filetype=php
> au BufNewFile,BufRead *.inc set filetype=php
> au BufNewFile,BufRead *.install set filetype=php
> 
> set nowrap
> set number
> set splitright

This will:

* Expand literal tabs to 2 spaces, while inserted tabs will be 2 actual spaces
* Ensure .module, .inc, and .install files are recognized as PHP files
* Disable line wrap, enable line numbers, and set vsplit to open new windows to the right of the current window

**Comment by mshade** [comment]
We want to discourage editing / committing directly from within the vm. While I use these features and niceties myself, I don't think we want to maintain config management just for details like this. You are free to copy in your ~/.vimrc and work as you like.
