### ISSUE TITLE
Capistrano generator doesn't work anymore

### ISSUE THREAD

**Issue by fafnirical** [forumone/generator-web-starter#89]
I don't have the exact error message, but it seems that after running the generator and selecting `capistrano`, there are some missing files, which prevents Capistrano from running correctly: https://github.com/forumone/web-starter/tree/1.1.x/lib.

**Comment by fafnirical** [comment]
Looks like the generator used to pull down forumone/web-starter, but it doesn't anymore as of  https://github.com/forumone/generator-web-starter/commit/28e58b784740fafc0a448d2fac569e6c3e13c78e. Since `generator-web-starter-capistrano` doesn't have the `lib` folder in its templates, the generated project ends up missing them.

**Comment by mortona42** [comment]
There is no error message - the rake files used in deployment are not there, so nothing happens.

**Comment by mshade** [comment]
The /capistrano and /lib templates have been added in the v0.2.8 release of the generator-web-starter-capistrano npm module that was just published. 'sudo npm install -g generator-web-starter' should pick it up.
